imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.upload_directory: '%kernel.project_dir%/web/uploads'


framework:
    esi: { enabled: true }
    fragments: { path: /_fragment }
    default_locale: pl
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'form/fields.html.twig'
    globals:
        upload_directory: '%app.upload_directory%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: '%kernel.root_dir%/Resources/java/compiler.jar'
        #yui_css:
        #    jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-grid.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-reboot.css'
            filters: [cssrewrite]
        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'
        tagsinput_css:
            inputs:
                - '%kernel.root_dir%/../app/Resources/public/tagsinput/*.css'
        tagsinput_js:
            inputs:
                - '%kernel.root_dir%/../app/Resources/public/tagsinput/*.js'

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    language: '%locale%'
    theme:
        simple:
            menu:
                edit: {title: 'Edit', items: 'undo redo | cut copy paste'}
                insert: {title: 'Insert', items: 'hr | pagebreak | charmap nonbreaking'}
                view: {title: 'View', items : 'visualaid | preview | code'}
                style: {title: 'Format', items: 'bold italic underline strikethrough superscript subscript | formats | removeformat'}
                table: {title: 'Table' , items: 'inserttable tableprops deletetable | cell row column'}
            plugins:
                - "hr, link, lists, charmap, nonbreaking, preview, code, table, pagebreak, emoticons, textcolor, nonbreaking"
            toolbar: "undo redo | bold italic underline strikethrough | forecolor backcolor | fontselect fontsizeselect | removeformat | bullist numlist | alignleft aligncenter alignright alignjustify | link emoticons"

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "noreply@citizens.pl"
        sender_name: "Citizens of Dalaran - do not reply"
    registration:
        form:
            type: UserBundle\Form\RegistrationType
    profile:
        form:
            type: UserBundle\Form\ProfileType

easy_admin:
    site_name: '<img src="../app/Resources/public/images/logo.png" class="d-inline-block" width="30" height="30" alt="Citizens of Dalaran logo" /> Citizens of Dalaran'
    design:
        brand_color: 'purple'
        menu:
            - { label: 'title.homepage', route: 'homepage', icon: 'home' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'News', icon: 'newspaper-o' }
            - { entity: 'Event', icon: 'calendar' }
    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y H:i:s'
    entities:
        News:
            class: AppBundle\Entity\News
            image_base_path: '/uploads/news/images/'
            list:
                fields:
                    - title
                    - { property: 'imagePath', type: 'image'}
                    - createdDate
                    - creator
                    - modifiedDate
                    - modifier
            edit:
                fields:
                    - title
                    - imagePath
                    - { property: 'summary', type: 'ckeditor' }
                    - { property: 'content', type: 'ckeditor' }
        User:
            class: UserBundle\Entity\User
            image_base_path: '/uploads/user/profilepics/'
            list:
                fields: 
                    - username
                    - { property: 'profilePicturePath', type: 'image'}
                    - roles
                    - { property: 'email', type: 'email' }
                    - enabled
                    - createdDate
                    - lastLogin
                    - name
                    - dateOfBirth
                    - { property: 'phoneNumber', type: 'tel' }
                    - { property: 'emergencyPhone', type: 'tel' }
            edit:
                fields:
                    - username
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_REDACTOR': 'ROLE_REDACTOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - username
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_REDACTOR': 'ROLE_REDACTOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }

        Event:
            class: AppBundle\Entity\Event