imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    default_locale: pl
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'form/fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: '%kernel.root_dir%/Resources/java/compiler.jar'
        #yui_css:
        #    jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-grid.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-reboot.css'
            filters: [cssrewrite]
        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'
        tagsinput_css:
            inputs:
                - '%kernel.root_dir%/../app/Resources/public/tagsinput/*.css'
        tagsinput_js:
            inputs:
                - '%kernel.root_dir%/../app/Resources/public/tagsinput/*.js'

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ".tinymce"
    language: '%locale%'
    theme:
        simple:
            menu:
                edit: {title: 'Edit', items: 'undo redo | cut copy paste'}
                insert: { title: 'Insert', items: 'hr | pagebreak | charmap' }
                view: { title : 'View', items : 'visualaid | preview | code' }
                table: { title : 'Table' , items: 'inserttable tableprops deletetable | cell row column' }
            plugins:
                - "hr, link, lists, charmap, nonbreaking, preview, code, table, pagebreak, emoticons, textcolor"
            toolbar: "undo redo | bold italic underline strikethrough | forecolor backcolor | fontselect fontsizeselect | removeformat | bullist numlist | alignleft aligncenter alignright alignjustify | link emoticons"

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "noreply@citizens.pl"
        sender_name: "Citizens of Dalaran - do not reply"
    registration:
        form:
            type: UserBundle\Form\RegistrationType
    profile:
        form:
            type: UserBundle\Form\RegistrationType