<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use AppBundle\Entity\Event;
use UserBundle\Entity\User;


/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Event::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('event')->orderBy('event.dateStart', 'DESC');
    }

    /**
     * Find all posts created or modified by user
     * @param integer $max
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findUpcoming($max)
    {
        $query = $this->createQueryBuilder('event')
            ->select('event.id, event.dateStart, event.name, event.summary')
            ->orderBy('event.dateStart', 'ASC')
            ->where('event.dateStart > :now')
            ->setMaxResults($max)
            ->setParameters(['now' => new \DateTime('now')])
            ->getQuery();

        return $query->execute();
    }

    /**
     * Save entity.
     *
     * @param \AppBundle\Entity\Event $event Event entity
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Event $event)
    {
        $this->_em->persist($event);
        $this->_em->flush($event);
    }

    /**
     * Delete entity.
     *
     * @param \AppBundle\Entity\Event $event Event entity
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function delete(Event $event)
    {
        $this->_em->remove($event);
        $this->_em->flush();
    }
}
